default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: association_development
test:
  <<: *default
  database: association_test

production:
  <<: *default
  database: association_production
  username: association
  password: <%= ENV['ASSOCIATION_DATABASE_PASSWORD'] %>
